## Importing the Packages

In [1]:
import numpy as np

In [10]:
np.set_printoptions(suppress = True , precision=2, linewidth=100)

## Importing the Data

In [11]:
raw_data_np = np.genfromtxt("loan-data.csv", delimiter = ';', skip_header=1, autostrip=True)

raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [12]:
np.isnan(raw_data_np).sum()

88005

In [13]:
temporary_fill = np.nanmax(raw_data_np) + 1

temporary_mean = np.nanmean(raw_data_np, axis= 0)

<ipython-input-13-70b54ee63d0a>:3: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data_np, axis= 0)


In [14]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [15]:
temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
                           temporary_mean,
                           np.nanmax(raw_data_np,axis=0)])

<ipython-input-15-35fc6d138540>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data_np, axis=0),
<ipython-input-15-35fc6d138540>:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np,axis=0)])


In [16]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [17]:
columns_string = np.argwhere(np.isnan(temporary_mean)).squeeze()

columns_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [18]:
columns_numeric = np.argwhere(np.isnan(temporary_mean)== False).squeeze()

columns_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Re-importing the Dataset

In [19]:
loan_data_string = np.genfromtxt("loan-data.csv", 
                                 delimiter = ';',
                                 dtype = np.str_,
                                 skip_header=1,
                                 usecols= columns_string,
                                 autostrip=True)

loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [20]:
loan_data_numeric = np.genfromtxt("loan-data.csv", 
                                 delimiter = ';',
                                 skip_header=1,
                                 usecols= columns_numeric,
                                 filling_values= temporary_fill,
                                 autostrip=True)

loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The Names of the Columns

In [21]:
headers = np.genfromtxt("loan-data.csv", 
                                 delimiter = ';',
                                 skip_footer= raw_data_np.shape[0],
                                 dtype = np.str_,
                                 autostrip=True)
headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [22]:
header_string, header_numeric = headers[columns_string],headers[columns_numeric]

In [23]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [24]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints:

In [25]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [26]:
string_checkpoint_test = checkpoint("string-checkpoint-test",header_string,loan_data_string)

In [27]:
string_checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [28]:
string_checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

## Manipulating String Columns

In [29]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [30]:
header_string[0] = "issue_date"

In [31]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [32]:
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [33]:
loan_data_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [34]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [35]:
loan_data_string[:,0] = np.chararray.strip(loan_data_string[:,0],"-15")

In [36]:
loan_data_string[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [37]:
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [38]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [39]:
for i in range(13):
        loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i],
                                          i,
                                          loan_data_string[:,0])

In [40]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [41]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [42]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [43]:
bad_loan_status = ['', 'Charged Off', 'Default', 'Late (31-120 days)']

In [44]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1],bad_loan_status),0,1)

In [45]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [46]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [47]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [48]:
loan_data_string[:,2] = np.chararray.strip(loan_data_string[:,2]," months")

In [49]:
np.unique(loan_data_string[:,2])

array(['', '36', '60'], dtype='<U69')

In [50]:
header_string[2]= "term_month"

In [51]:
loan_data_string[:,2] = np.where(loan_data_string[:,2] =='',
                                '60',
                                loan_data_string[:,2])

In [52]:
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

In [53]:
header_string

array(['issue_date', 'loan_status', 'term_month', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

### Grade and Subgrade

In [54]:
np.unique(loan_data_string[:,3],return_counts= True)

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),
 array([ 515, 1632, 2606, 2766, 1389,  816,  236,   40], dtype=int64))

In [55]:
np.unique(loan_data_string[:,4],return_counts= True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([514, 285, 278, 239, 323, 502, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

In [56]:
for i in np.unique(loan_data_string[:,3])[1:]:
    
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i),
                                    i+ '5',
                                    loan_data_string[:,4])

In [57]:
np.unique(loan_data_string[:,4],return_counts= True) 

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [58]:
loan_data_string[:,4] = np.where(loan_data_string[:,4] == '',
                                 'H1',
                                 loan_data_string[:,4])

In [59]:
np.unique(loan_data_string[:,4],return_counts= True) 

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

#### Filling Sub Grade

In [60]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                      i + '5',
                                      loan_data_strings[:,4])

NameError: name 'loan_data_strings' is not defined

#### Removing Grade

In [61]:
loan_data_string = np.delete(loan_data_string,3,axis= 1)

In [62]:
header_string = np.delete(header_string,3)

In [63]:
header_string

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [64]:
header_string[3]

'sub_grade'

#### Converting Sub Grade

In [65]:
np.unique(loan_data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [66]:
values = list(range(1,np.unique(loan_data_string[:,3]).shape[0]+ 1))


In [67]:
keys = list(np.unique(loan_data_string[:,3]))

In [68]:
dict_sub_grade = dict(zip(keys,values))

In [69]:
for i in np.unique(loan_data_string[:,3]):
    
    
    loan_data_string[:,3] = np.where(loan_data_string[:,3] == i,
                                    dict_sub_grade[i],
                                    loan_data_string[:,3])

In [70]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [71]:
keys = list(np.unique(loan_data_strings[:,3]))                         
values = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1)) 
dict_sub_grade = dict(zip(keys, values))

NameError: name 'loan_data_strings' is not defined

In [72]:
for i in np.unique(loan_data_strings[:,3]):
        loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i, 
                                          dict_sub_grade[i],
                                          loan_data_strings[:,3])

NameError: name 'loan_data_strings' is not defined

### Verification Status

In [73]:
header_string

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [74]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'),
 array([ 500, 2673, 4116, 2711], dtype=int64))

In [75]:
loan_data_string[:,4] = np.where((loan_data_string[:,4] == '')| (loan_data_string[:,4] =='Not Verified'),
                                0,
                                1)

In [76]:
np.unique(loan_data_string[:,4], return_counts= True)

(array(['0', '1'], dtype='<U69'), array([3173, 6827], dtype=int64))

### URL

In [77]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [78]:
loan_data_string[:,5] = np.chararray.strip(loan_data_string[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=' )

In [79]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [80]:
loan_data_string[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [81]:
headers

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [82]:
loan_data_numeric[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [83]:
np.array_equal(loan_data_numeric[:,0].astype(dtype = np.int32),loan_data_string[:,5].astype(dtype = np.int32))

True

In [84]:
loan_data_string=np.delete(loan_data_string,5,axis=1)

In [85]:
header_string=np.delete(header_string,5)

In [86]:
header_string

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [87]:
loan_data_string

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

### State Address

In [88]:
header_string

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [89]:
header_string[5] = "state_address"

In [90]:
header_string 

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [91]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [92]:
state_code, state_count = np.unique(loan_data_string[:,5], return_counts= True)

In [93]:
state_code, state_count

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [94]:
state_count[np.argsort(-state_count)]

array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
        216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
         84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
         25,   24,   17,   16,   10], dtype=int64)

In [95]:
state_count_sorted = np.argsort(-state_count)

In [96]:
state_code[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [97]:
loan_data_string[:,5] = np.where(loan_data_string[:,5] == '', 
                                 0, 
                                 loan_data_string[:,5])

In [98]:
np.unique(loan_data_string[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [99]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

In [100]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west),1,loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south),2,loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest),3,loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east),4,loan_data_string[:,5])


In [101]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [102]:
loan_data_string= loan_data_string.astype(dtype = np.int32)

In [103]:
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [104]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [105]:
checkpoint_string = checkpoint("checkpoint-string", header_string, loan_data_string)

In [106]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [107]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Manipulating Numeric Columns

In [108]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [109]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [110]:
np.isnan(loan_data_numeric).sum()

0

### Substitute "Filler" Values

In [111]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [112]:
temporary_fill

68616520.0

In [113]:
np.isin(loan_data_numeric[:,0],temporary_fill).sum()

0

In [114]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [115]:
temporary_stats[:,columns_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [116]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### Temporary Stats

#### Funded Amount

In [117]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                 temporary_stats[0,columns_numeric[2]],
                                 loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [118]:
temporary_stats[2,columns_numeric[3]]

28.99

In [119]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill, 
                                  temporary_stats[0, columns_numeric[2]],
                                  loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [120]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [121]:
for  i in [1,3,4,5]:
    
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                     temporary_stats[2,columns_numeric[i]],
                                     loan_data_numeric[:,i])

In [122]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Currency Change

#### The Exchange Rate

In [123]:
EUR_USD = np.genfromtxt("EUR-USD.csv", delimiter= ',',skip_header=1, usecols=3 ,autostrip=True)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [126]:
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [130]:
loan_data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [132]:
exchange_rate = loan_data_string[:,0]

In [134]:
for i in range(1,13):
    
    exchange_rate = np.where(exchange_rate == i,
                            EUR_USD[i-1],
                            exchange_rate)

In [138]:
np.unique(exchange_rate)

array([0.  , 1.06, 1.08, 1.09, 1.09, 1.1 , 1.1 , 1.11, 1.12, 1.12, 1.13, 1.13, 1.13])

In [141]:
exchange_rate = np.where(exchange_rate == 0,
                             np.mean(EUR_USD).round(2),
                             exchange_rate)    

In [143]:
np.unique(exchange_rate)

array([1.06, 1.08, 1.09, 1.09, 1.1 , 1.1 , 1.11, 1.11, 1.12, 1.12, 1.13, 1.13, 1.13])

In [144]:
exchange_rate.shape

(10000,)

In [148]:
exchange_rate = np.reshape(exchange_rate,(10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

# -- do not run np.hstack() or np.concatenate() multiple times as it will add every time it runs

In [163]:
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,        1.1 ,        1.1 ,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,        1.11,        1.11,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,        1.13,        1.13,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,        1.12,        1.12,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,        1.11,        1.11,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,        1.09,        1.09,        1.09]])

In [167]:
loan_data_numeric.shape

(10000, 10)

In [169]:
loan_data_numeric = np.delete(loan_data_numeric,[7,8,9], axis = 1)

In [171]:
loan_data_numeric.shape

(10000, 7)

In [179]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [152]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [165]:
header_numeric = np.concatenate((header_numeric, np.array(["exchange_rate"])))

In [176]:
header_numeric = np.delete(header_numeric,[7])

In [191]:
header_numeric.shape

(7,)

#### From USD to EUR

In [178]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [181]:
columns_dollar = np.array([1,2,4,5])

In [182]:
loan_data_numeric[:,columns_dollar]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [183]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [192]:
(loan_data_numeric[:,1]/loan_data_numeric[:,6]).shape

(10000,)

In [187]:
columns_dollar

array([1, 2, 4, 5])

In [188]:
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], (10000,1))))

In [189]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27027.03,      845.56,     4215.95],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [190]:
loan_data_numeric.shape

(10000, 11)

#### Expanding the header

In [193]:
header_numeric[columns_dollar]

array(['loan_amnt', 'funded_amnt', 'installment', 'total_pymnt'], dtype='<U19')

In [195]:
header_additional = np.array([col_name+'_EUR' for col_name in header_numeric[columns_dollar]])

In [197]:
header_additional.shape

(4,)

In [199]:
header_numeric = np.hstack((header_numeric, header_additional))

In [200]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [202]:
header_numeric.shape

(11,)

In [204]:
header_numeric[columns_dollar] = np.array([col_name+'_USD' for col_name in header_numeric[columns_dollar]])

In [244]:
header_numeric

array(['id', 'loan_amnt_USD', 'exchange_rate', 'total_pymnt_EUR', 'funded_amnt_USD',
       'installment_EUR', 'int_rate', 'installment_USD', 'loan_amnt_EUR', 'funded_amnt_EUR',
       'total_pymnt_USD'], dtype='<U19')

In [245]:
header_numeric.shape

(11,)

In [250]:
a=list(enumerate(header_numeric))
a

[(0, 'id'),
 (1, 'loan_amnt_USD'),
 (2, 'exchange_rate'),
 (3, 'total_pymnt_EUR'),
 (4, 'funded_amnt_USD'),
 (5, 'installment_EUR'),
 (6, 'int_rate'),
 (7, 'installment_USD'),
 (8, 'loan_amnt_EUR'),
 (9, 'funded_amnt_EUR'),
 (10, 'total_pymnt_USD')]

In [251]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [252]:
header_numeric[columns_index_order]

array(['id', 'loan_amnt_USD', 'installment_USD', 'exchange_rate', 'loan_amnt_EUR',
       'total_pymnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_USD', 'int_rate'], dtype='<U19')

In [243]:
header_numeric = header_numeric[columns_index_order]
header_numeric

array(['id', 'loan_amnt_USD', 'exchange_rate', 'total_pymnt_EUR', 'funded_amnt_USD',
       'installment_EUR', 'int_rate', 'installment_USD', 'loan_amnt_EUR', 'funded_amnt_EUR',
       'total_pymnt_USD'], dtype='<U19')

In [221]:
loan_data_numeric = loan_data_numeric[:,columns_index_order]

### Interest Rate

In [225]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [227]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [228]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### Checkpoint 2: Numeric

In [229]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [231]:
checkpoint_numeric = checkpoint("checkpoint-numeric",header_numeric,loan_data_numeric)

In [238]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27027.03, ...,     4679.7 ,     4215.95,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the "Complete" Dataset

In [249]:
np.vstack((checkpoint_numeric['header'],checkpoint_numeric['data'].round(2)))

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'total_pymnt_USD', 'total_pymnt_EUR',
        'exchange_rate'],
       ['48010226.0', '35000.0', '31933.3', ..., '9452.96', '8624.69', '1.1'],
       ['57693261.0', '30000.0', '27027.03', ..., '4679.7', '4215.95', '1.11'],
       ...,
       ['50415990.0', '10000.0', '8910.3', ..., '2185.64', '1947.47', '1.12'],
       ['46154151.0', '35000.0', '31490.9', ..., '3199.4', '2878.63', '1.11'],
       ['66055249.0', '10000.0', '9145.8', ..., '301.9', '276.11', '1.09']], dtype='<U32')

In [3]:
checkpoint-numeric['header']

NameError: name 'checkpoint' is not defined

In [6]:
checkpoint_numeric = np.load('checkpoint-numeric.npz')

In [8]:
checkpoint_numeric['header']

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD',
       'funded_amnt_EUR', 'int_rate', 'installment_USD',
       'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
       'exchange_rate'], dtype='<U19')

In [11]:
checkpoint_numeric['data']

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27027.03, ...,     4679.7 ,     4215.95,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

In [12]:
checkpoint_string = np.load('checkpoint-string.npz')

In [13]:
checkpoint_string['header']

array(['issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [14]:
checkpoint_string['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [17]:
loan_data = np.hstack((checkpoint_numeric['data'],checkpoint_string['data']))
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27027.03, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [25]:
header_full = np.hstack((checkpoint_numeric['header'],checkpoint_string['header']))
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [26]:
np.concatenate((checkpoint_numeric['header'],checkpoint_string['header']))

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_month', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

## Sorting the New Dataset

In [30]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [31]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [32]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## Storing the New Dataset

In [34]:
loan_data = np.vstack((header_full,loan_data))

In [35]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [36]:
np.savetxt("loan_data_processed.csv", loan_data,fmt= '%s', delimiter = ',')